### ISSUE TITLE
D0S.Factory - Active crafting prevents scripted window opening of Factory window.

### ISSUE THREAD

**Issue by NickGrease** [d0sboots/PerfectTower#12]
If D0S.Factory is actively crafting and the Factory window is closed, another script that attempts to open the factory window will fail to do so. I've tried to use my limited knowledge to work around this to no avail. I have a feeling it may be a technical limitation, but thought I'd report it all the same.

**Comment by d0sboots** [comment]
Sorry for the late reply.

This works fine for me. Here's my test script:
```
BFRlc3QBAAAABWtleS5iAAAAAAEAAAAQdG93bi53aW5kb3cuc2hvdwhjb25zdGFudAQHZmFjdG9yeQhjb25zdGFudAEB
```
If I leave the factory while it's crafting and then hit "b", I return to the factory.

**Comment by NickGrease** [comment]
Thanks for your reply. It was indeed the screen switching, even though I included waits before and after window open/closes, it appears that closing my mine window caused a stutter in the window animation occasionally, and that stutter was just long enough that the call to open the factory window happened while the mine window was still closing. Slightly longer waits solved the issue.
