### ISSUE TITLE
Factory not crafting chips

### ISSUE THREAD

**Issue by CleanCutBloons** [d0sboots/PerfectTower#14]
When I try to craft a machine, sometimes it will not try to craft the chips required. 
For example, crafting T4 mixer:
![image](https://user-images.githubusercontent.com/61286931/227624207-39e79fa8-7148-4e4c-9c1f-0afd3e881f97.png)
Then I tried crafting the chips, and it didn't have the materials to.

**Comment by d0sboots** [comment]
You only have 1T2/T3/T4 dust, and 483 T1 dust. I would expect it to tell you that you lack dust if you try to craft a T4 mixer.

**Comment by CleanCutBloons** [comment]
This was after I tried to craft. All the components are crafted except the advanced chips. The script worked fine until it reached the chips, it seems to not even factor them into the cost of the machine. When I tried to craft the chips, it said there were not enough materials for them. I have no idea why it didn't tell me beforehand.

**Comment by d0sboots** [comment]
Do you have the Chemical Lumps exotic skill? The script assumes you do, if you don't then uptiering will be much more expensive than it expects, so what it thinks is enough resources won't be.

**Comment by d0sboots** [comment]
I'm going to assume that was it.
