### ISSUE TITLE
D0S.Factory Bug

### ISSUE THREAD

**Issue by tntdog99** [d0sboots/PerfectTower#17]
when i try making a mixer don't know about other machines one time is made a arcade producer and now its made a trading post producer i don't know what to do

**Comment by d0sboots** [comment]
I can't quite tell what issue you are having. Is it that you are having trouble with the interface? You use the WASD keys to select what it will make, the items are split into various categories that you can move through with W/S for up/down and A/D for left/right to select different options.

Hope this helps!

**Comment by tntdog99** [comment]
i know what is was it was a worker mining clusters

**Comment by tntdog99** [comment]
i know what is was it was a worker mining clusters
