### ISSUE TITLE
Autotrasher - Line 70 just f*cked me :(

### ISSUE THREAD

**Issue by Mikrowellenmann** [d0sboots/PerfectTower#18]
In the customizeable workspace of the Autotrasher, the "click me to change configuration", line 70, "circuit" instead of "wires.circuit".
Just deleted 100m t1 circuit wires i prepared to craft with :/

**Comment by d0sboots** [comment]
I'm sorry you had a bad experience, but it does say (in multiple places):
"The default configuration is: It keeps T5 of all producers, gem/exo producers, T10 of all machines, all tiers of chips, T8,9,10 of ingots, rubber, and all tiers of ore, dust, and lumps. **Everything else is trashed.**"

T1 circuit wires is definitely part of "everything else." :(

**Comment by Mikrowellenmann** [comment]
That wasn't the point i was trying to make, i probably phrased it wrong so my bad.
What i was trying to point out is that in the workspace import code you provided for the Autotrasher is a mistake.
In line 70 the item "circuit" is mentioned, which doesn't exist. I presume this should be "wires.circuit" as circuit wires aren't mentioned anywhere else. Me not knowing anything about coding and trusting as i am i just changed all the numbers without double checking the names.
So it deleted all my circuit wires even tho i adjusted the numbers.
I triple checked if it was me that somehow created this error but it was always there form the import.
No hate to you, even if, now that i read my first comment again, it slightly came of that way.
Ty very much for this and all the other provided codes :)

**Comment by d0sboots** [comment]
Can you paste what you changed it to? I can assure you, "circuit" is the correct name.

**Comment by Mikrowellenmann** [comment]
No you're right, thats a complete screwup of my coding skills.
I think what happend is that with circuit wires not beeing "wires.circuit" i completely missed it the first time, deleting all but the t10s. And the second time i changed it to "wires.circuit" "" resulting in not deleting anything just like i wanted and thinking i did it right. 
Sooo my bad xD 
still ty for trying to help and the codes :)
