### ISSUE TITLE
Needs Ore Lump Crafting

### ISSUE THREAD

**Issue by Xaralabos23** [d0sboots/PerfectTower#2]
Your 'factory_constants.tpt2' says it cant craft lumps cose there is no need for them, wrong,
u need 1000 of them for the Factory Floor 2 so u can 'learn it.
Lumps have half of their respective dust plus they give 2 dusts so technically u get 4 times value if u craft lumps by using the Fabricator.

It kind of sucks if u have millions of dusts and u have to click 1 by 1 to get 1000.

**Comment by d0sboots** [comment]
When I said they weren't needed, I meant that they aren't blocking other items from being scanned. Yes, they are still something to be scanned for themselves, and I do hope to add them someday.
