### ISSUE TITLE
Trading Post Crate Spam not working

### ISSUE THREAD

**Issue by UncleDolan1** [d0sboots/PerfectTower#20]
Keeps asking for Turbo Exec 2.2, even when installed and enabled or installed and disabled
tried removing and replacing them, turbo exec 2.2 works since other scripts that require it, do in fact work

**Comment by d0sboots** [comment]
There is almost certainly something wrong with your installation of turbo exec, or you haven't restarted the AI (F4/F4) since you installed it. Attach a screenshot of your scripts with the TE folder expanded and I might be able to help further.

**Comment by UncleDolan1** [comment]
Forgot to mention that i reseted the game, the computer, tried to reisntall several times. Still did not work:
I've attached screenshots of all the scripts and of the error message. thank you for the assistance
![turned off1](https://github.com/d0sboots/PerfectTower/assets/154702426/36ee0307-3dfa-437f-a39e-314960a49e37)
![turned off2](https://github.com/d0sboots/PerfectTower/assets/154702426/e2d611a2-024a-45e3-944d-3b8c98e777be)
![Allscripts](https://github.com/d0sboots/PerfectTower/assets/154702426/4ecebd5a-f6a5-4f7e-a7bb-55511f042a67)
![errormessage](https://github.com/d0sboots/PerfectTower/assets/154702426/8dc636bc-a332-433e-9712-577d1a90decc)

**Comment by d0sboots** [comment]
The scripts are disabled (red with line through them), so of course they won't work. Also, it looks like you have (at least) two copies of turbo exec.

Delete the TE2.2 folder and the other turbo scripts, re-import turbo *one* more time, and then enable all its scripts (you can toggle the whole folder at once by right clicking).
