### ISSUE TITLE
[Feature Request- Factory Automation] Auto-buy rubber if short.

### ISSUE THREAD

**Issue by brknsoul** [d0sboots/PerfectTower#21]
The Factory Automation script should attempt to purchase Rubber if it's short.

**Comment by d0sboots** [comment]
Buying from the shop is out of scope for the factory script. (It's nearly impossible to do, and can't be done as efficiently because AI can't right-click.)

**Comment by brknsoul** [comment]
Yah, I noticed this when trying to make that script myself.. kinda annoying, hopefully the revamp will solve things.

**Comment by d0sboots** [comment]
The easiest automatic way to buy rubber is with an auto clicker script, but it's slow. With the infinite rubber skill, you can just right-click 10 times and get plenty of rubber to tide you over for a while.
