### ISSUE TITLE
Making random pipes

### ISSUE THREAD

**Issue by drago87** [d0sboots/PerfectTower#5]
When using the Factory automation script and making bulk items it sometimes makes pipes resulting in it missing items for the actual craft

**Comment by d0sboots** [comment]
Gonna need some more info to debug this. Can you attach a screenshot of your full factory when it is running? (Use Shift+Win+S or Alt+PrtScr). What are the bulk items that you are trying to make? (Including tier?)
Also, (unlikely), but double-check that the pipes aren't coming from the asteroid mine.

**Comment by drago87** [comment]
Havent unlocked the astroid mine yet so thats a no. As for items it have happened when doing enything realy the latest was 1000 T1 chips and before that 1000 T1 blocks. But also happens when doing 7 T4 Red pruducers. The tier of the pipes is usualy of the tier of the item crafted but sometimes if i make a T4 Red pruducer it can make a T3 or T4 pipe when making the T2 Chip. As for a screenshot that will have to wait. Are out of material and the next Refining is done in about 55h

**Comment by d0sboots** [comment]
I double-checked all the scenarios you listed: 1000x T1 chip, 1000x T1 block, and 7x T4 red_producer. None of the make spurious pipes for me. Making individual T4 red_producers creates 1 extra T1 cable, 1 T2 rod, and 3 T2 screws; these are used up if you make producers in multiples of 8.

Whatever you're seeing, it seems specific to something in your setup. I'll need that screenshot to go further. One thing that might help diagnose now is if you could get a screenshot of your current scripts list; that might reveal something. Drag the window down and/or squish it horizontally to get them all to show in one picture.

**Comment by drago87** [comment]
The module farming script was added today so i had the probel before it
![Scripts](https://user-images.githubusercontent.com/6805712/156468813-df535daa-05bb-4f34-9383-2cc60657c641.png)

The T2 pipes where made when doing the T1 chips
![Factory](https://user-images.githubusercontent.com/6805712/156468892-f04fc753-ca39-4a66-831a-271d565a246b.png)

**Comment by d0sboots** [comment]
OK, I see I problem. You have put turbo exec into a package. It will not work this way; I imagine that when you run the factory, it runs very slowly. I'm not 100% certain that this is what's causing the pipes issue, but I think it's pretty likely. (Also, fixing it will make everything go much faster.)

Delete your "Turbo Exec v2" package and re-import turbo-exec from the bundle import.

**Comment by d0sboots** [comment]
I'm going to assume that solved the issue.
