### ISSUE TITLE
Factory automation - Works for a bit, then just stops with no additional messages

### ISSUE THREAD

**Issue by pnomolos** [d0sboots/PerfectTower#6]
For example, I have set up to build a T4 oven.  The automation will work until a T3 oven is built (and in the inventory) and then it just stops, without further information.

**Comment by d0sboots** [comment]
Gonna need some more info to debug this. Can you attach a screenshot of your full factory when it is running? (Use Shift+Win+S or Alt+PrtScr). Another thing that might help is if you could get a screenshot of your current scripts list; that might reveal something. Drag the window down and/or squish it horizontally to get them all to show in one picture.

**Comment by pnomolos** [comment]
Factory (trying to upgrade to T4 boiler):

![image](https://user-images.githubusercontent.com/36223/156661760-7df3c60c-6051-47be-bbbf-b87cfd134403.png)

Scripts:

![image](https://user-images.githubusercontent.com/36223/156661964-b2ed9bb7-77b9-47db-9653-8619b7be2816.png)

Above the top script is "Turbo Start" and below is the "D0S.Factory V2.2.0" folder.  No other scripts.

**Comment by pnomolos** [comment]
Boiler upgrade got to T3 and then just stopped.  Tried F4 on/off and restarting and no dice.  If I trash the T3 boiler (or put it back into the active machine area) then starting the factory again works - but it's then trying to make a fresh one from scratch rather than upgrading.

I also checked in case it was some sort of off-by-one error, but changing the target to a T5 boiler didn't change the behaviour - it still stopped at T3.

**Comment by pnomolos** [comment]
It seems to be working now, so I'm going to close this.  The only thing different (as far as I know) is that I was no longer in the middle of refining shards - so perhaps that had something to do with it?

**Comment by pnomolos** [comment]
@d0sboots As a follow-up to this - I think if you are refining shards (or have refined ore still in the refining area) the script sees those as available, but the game doesn't let you pull them out, which causes it to get stuck.

**Comment by d0sboots** [comment]
Hmm, I don't think that's it, or at least it doesn't seem to be it for me. I refined a chunk of ore, left it sitting there, but everything was working properly.

Do you have the exotic skill "chemical lumps"? It's required, and someone else had issues very much like yours recently, due to not having it.
