### ISSUE TITLE
Fails to import

### ISSUE THREAD

**Issue by fozzibab** [d0sboots/PerfectTower#9]
I realize the last updates made to your scripts were probably around Feb, but at least one of them (Auto Museum combiner) is failing to import on the latest build of the game. Do you have any intent on updating or can we assume these scripts are DOA?

Thanks!

**Comment by d0sboots** [comment]
As you can see from the [commit history](https://github.com/d0sboots/PerfectTower/commits/main), I've been steadily working on this the whole time.

Are you using the "copy icon" to copy the string? Double-click is unreliable, it won't get everything. You can also triple-click.

**Comment by fozzibab** [comment]
Apologies, took me a while to get back to this. The "Copy" icon in the script box was the key. Seems to be working brilliantly. Thanks for this!
